language: go

go:
  - 1.13.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:
  - go get -t -v ./...

script:
  - make setup && make build
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    skip_cleanup: true
    on:
      branch: master
      tags: true
      repo: thamaraiselvam/github-api-cli
      condition: $GORELEASER_ON = 1